export { ReactComponent as ProfileIcon } from "./profile.svg";
export { ReactComponent as LockIcon } from "./lock.svg";
export { ReactComponent as MessageIcon } from "./message.svg";
export { ReactComponent as ArrowRightIcon } from "./arrow-right.svg";
export { ReactComponent as UserIcon } from "./user.svg";
export { ReactComponent as ShowIcon } from "./show.svg";
export { ReactComponent as SendIcon } from "./send.svg";
export { ReactComponent as CloseSquareIcon } from "./close-square.svg";
export { ReactComponent as DownloadIcon } from "./download.svg";
